---
- name: install package smokeping and dependencies
  apt: pkg={{ item  }} state=installed
  with_items:
    - apache2
    - smokeping
    
#- name: symbolic link of smokeping config for apache2
#  file: src=/etc/smokeping/apache2.conf dest=/etc/apache2/conf-available/smokeping.conf state=link
#  notify: restart apache
#- name: Enable --nosleep smokeping
#  replace:
#         dest: '/etc/init.d/smokeping'
#         regexp: 'start-stop-daemon --start' 
#         replace: 'start-stop-daemon --nosleep --start'
#         #backup: yes
#         #backrefs: yes
 
- name: Disable syslog
  lineinfile:
         dest: '/etc/smokeping/config.d/General'
         regexp: 'syslogfacility = local0'
         line: '#syslogfacility = local0'
  
- name: enable apache2 smokeping config
  command: a2enconf smokeping creates=/etc/apache2/conf-enabled/smokeping.conf
  notify: restart apache

- name: enable apache2 module cgi 
  command: a2enmod cgid creates=/etc/apache2/mods-enabled/cgid.load
  notify: restart apache 
- name: Modify Database ping every second  
  template: src=etc/smokeping/config.d/Database dest=/etc/smokeping/config.d/Database
  notify: 
    - restart smokeping
- name: Enable --nosleep smokeping 
  template: src=etc/init.d/smokeping dest=/etc/init.d/smokeping
  notify: 
    - restart smokeping
- name: config file - Targets  
  template: src=etc/smokeping/config.d/Targets.j2 dest=/etc/smokeping/config.d/Targets
  notify: 
    - restart smokeping
    - restart apache
