---

- name: "Debian | Set some facts"
  set_fact:
    apache_log: apache2
    datafiles_path: "/usr/share/zabbix-proxy-{{ database_type }}"
  when:
    - zabbix_version | version_compare('3.0', '<')
  tags:
    - zabbix-server
    - init
    - config

- name: "Debian | Set some facts for Zabbix 3.0"
  set_fact:
    apache_log: apache2
    datafiles_path: "/usr/share/doc/zabbix-proxy-{{ database_type }}"
  when:
    - zabbix_version | version_compare('3.0', '>=')
  tags:
    - zabbix-server
    - init
    - config

- name: "Debian | Install gpg key"
  apt_key:
    id: 79EA5ED4
    url: http://repo.zabbix.com/zabbix-official-repo.key
  when:
    - zabbix_repo == "zabbix"

- name: "Debian | Installing repository non-free Debian"
  apt_repository:
    repo: "deb http://deb.debian.org/debian/ {{ ansible_distribution_release }} main contrib non-free"
    state: present
  when:
    - ansible_distribution == "Debian"
- name: "Debian | Installing repository Debian"
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/ {{ ansible_distribution_release }} main"
    state: present
  when:
    - ansible_distribution == "Debian"
    - zabbix_repo == "zabbix"

- name: "Debian | Installing repository Debian"
  apt_repository:
    repo: "deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/ {{ ansible_distribution_release }} main"
    state: present
  when:
    - ansible_distribution == "Debian"
    - zabbix_repo == "zabbix"

- name: "Debian | Installing repository Ubuntu"
  apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - zabbix_repo == "zabbix"

- name: "Debian | Installing repository Ubuntu"
  apt_repository:
    repo: "deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - zabbix_repo == "zabbix"

- name: "Debian | Installing zabbix-proxy-{{ database_type }}"
  apt:
    pkg: zabbix-proxy-{{ database_type }}
    update_cache: yes
    cache_valid_time: 3600
    force: yes
    state: present

- name: "Debian | Install Ansible module dependencies"
  apt:
    name: python-psycopg2
    state: present
  when:
    - zabbix_database_creation

- name: "Debian | Install Mysql Client package"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-client
    - python-mysqldb
  when:
    - database_type == 'mysql'
  tags:
    - zabbix-server
    - init
    - database

- name: "Debian | Install PostgreSQL Client package"
  apt:
    name: postgresql
    state: present
  when:
    - database_type == 'pgsql'
  tags:
    - zabbix-server
    - init

##Modify Dani for Cisco interface discovery
- name: Install packages
  apt: name={{ item }} state=latest
  with_items: 
          - snmp
          - snmp-mibs-downloader
          - ruby
          - gem

- name: "Debian | Download MIBS"
  shell: download-mibs

- name: "Debian | Download if.speed"
  get_url:
    url: https://raw.githubusercontent.com/jjmartres/Zabbix/master/zbx-scripts/if.speed/if.speed
    dest: /usr/lib/zabbix/externalscripts/if.speed
    mode: 0711

- name: Modify snmp.conf 
  lineinfile:
          dest: '/etc/snmp/snmp.conf'
          regexp: 'mibs :' 
          line: 'mibs +ALL' 
          backrefs: yes
- gem:
    name: snmp
    state: latest
