---
# task file for sqlite3

- name: "Sqlite3 | Default Database Path"
  set_fact:
    proxy_dbname: /var/lib/zabbix/zabbix_proxy.db
  when:
    - zabbix_proxy_dbname == "zabbix_proxy"

- name: "Sqlite3 | Create database"
  file:
    name: "{{ zabbix_proxy_dbname | dirname }}"
    owner: zabbix
    group: zabbix
    state: directory
  when:
    - zabbix_database_creation
