---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: zabbix-proxy-mysql-centos
    image: milcom/centos7-systemd
    privileged: True
    groups:
      - mysql
  - name: zabbix-proxy-pgsql-centos
    image: milcom/centos7-systemd
    privileged: True
    groups:
      - postgresql
  - name: zabbix-proxy-mysql-debian
    image: maint/debian-systemd
    privileged: True
    groups:
      - mysql
  - name: zabbix-proxy-pgsql-debian
    image: maint/debian-systemd
    privileged: True
    groups:
      - postgresql
  - name: zabbix-proxy-mysql-ubuntu
    image: solita/ubuntu-systemd
    privileged: True
    groups:
      - mysql
  - name: zabbix-proxy-pgsql-ubuntu
    image: solita/ubuntu-systemd
    privileged: True
    groups:
      - postgresql
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      mysql:
        database_type: mysql
        database_type_long: mysql
        server_dbport: 3306
      postgresql:
        database_type: pgsql
        database_type_long: postgresql

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
