---
- name: install pacpakges {{ item }}
  apt: name={{ item }}
  with_items:
    - lxc
    - lxc-dev
    - python-pip
  tags:
    - lxc_server

- name: copy file lxc-net
  template:
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}" 
  with_items:
    - { src: 'etc/default/lxc-net', dest: '/etc/default/lxc-net' }
    - { src: 'etc/lxc/default.conf', dest: '/etc/lxc/default.conf' }
  notify:
    - restart lxc-net
  tags:
    - lxc_server

- name: flush handlers
  meta: flush_handlers
  tags:
    - lxc_server

- name: pip lxc packages are installed on host
  pip:
    name: lxc-python2
  tags:
    - lxc_server

- name: enable ip forwading
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
  tags:
    - lxc_server
